### ISSUE TITLE
mongodb-core 2 doesn't catch count() callback exceptions

### ISSUE THREAD

**Issue by rahbari** [christkv/mongodb-core#120]
if an exception is thrown in mongojs count() callback function mongodb core 2 doesn't catch it, the callback execution is halted but node process continues to execute. On core 1 raised exception in callback functions stopped main process and was logged to console.

**This is the trace for version 1:**
ReferenceError: a is not defined
    at db.cars.count (/Users/User/Intellij/Start/routes/site.js:115:26)
    at /Users/User/Intellij/Start/node_modules/mongodb/lib/cursor.js:937:7
    at commandCallback (/Users/User/Intellij/Start/node_modules/mongodb-core/lib/topologies/server.js:1246:9)
    at Callbacks.emit (/Users/User/Intellij/Start/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at .messageHandler (/Users/User/Intellij/Start/node_modules/mongodb-core/lib/topologies/server.js:397:23)
    at Socket.<anonymous> (/Users/User/Intellij/Start/node_modules/mongodb-core/lib/connection/connection.js:302:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

**This is the trace for version 2 captured with internal try/catch:**
ReferenceError: a is not defined
    at db.cars.count.e (E:\Node\Start\routes\site.js:115:26)
    at Object.cb (E:\Node\Start\node_modules\mongodb\lib\cursor.js:942:7)
    at E:\Node\Start\node_modules\mongodb-core\lib\connection\pool.js:443:18
    at authenticateStragglers (E:\Node\Start\node_modules\mongodb-core\lib\connection\pool.js:399:16)
    at .messageHandler (E:\Node\Start\node_modules\mongodb-core\lib\connection\pool.js:421:5)
    at Socket.<anonymous> (E:\Node\Start\node_modules\mongodb-core\lib\connection\connection.js:294:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

I believe try and catch is missed while calling callback functions.

**Comment by christkv** [comment]
there is no catch at all, however 2.2.5 has just come out and allows for the use of domains again (see link below)

http://mongodb.github.io/node-mongodb-native/2.2/upgrade-migration/

**Comment by rahbari** [comment]
I don't get it, you mean there is no need to catch callback exceptions? Anyway version 1 of mongo core catches user callback exception and send it to node main loop!

```
      try {
        callback(null, new CommandResult(options.fullResult ? result : result.documents[0], result.connection));
      } catch(err) {
        process.nextTick(function() { throw err});
      }
```

**Comment by christkv** [comment]
I made a small improvement for mongodb-core you can use the 2.0 branch to test if it works for your case. I will be out for the next two weeks so don't expect a quick release for this issue.

**Comment by owenallenaz** [comment]
I'm a little confused on the intent here, of both the question and your fix. As the driver developer, I don't really think that you should be responsible for try/catching user-space code. If I use your driver, and I throw an error in my code, my process should crash. I don't quite understand the request from @rahbari because the issue says "doesn't catch count() callback exceptions" but he said that in version 1 it would cause a process crash, while in version 2 it does not. Well if the process *isn't* crashing on a thrown error, that means it is being caught. So there's some inconsistency there.

In my tests, using the version before your small fix and the version after, in both cases the process crashed, which is how it should behave in my eyes. If a developer wants to have large swaths of code wrapped in async try/catches, then it's up to the developer to properly implement domains.

I don't really think it's a good idea for you to have to pepper the code base with try/catches to account for user-side errors, unless there is a circumstance which a try/catch internal within the mongo driver is causing it to catch *my* errors. If so, then the proper tool is bouncing off the event loop so that your try/catches remain YOURS and developer try/catches remain ours. Each try/catch creates a v8 de-opt so it's best to keep them at a minimum.

**Comment by zbjornson** [comment]
I agree with @owenallenaz, I think this should be the user's responsibility.

Throwing inside `nextTick` (`process.nextTick(function () { throw err; })` as done in 338238b and @rahbari's example) I think also implies that the error handling would be done in `process.on("uncaughtException", ...)`, which is [bad practice](https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly).

**Comment by christkv** [comment]
There seems to be some situation where the user claims the throwing of an error does not crash the process. @rahbari  can you provide an actual code example of the claimed problem ?

**Comment by rahbari** [comment]
I didn't argue if catching exceptions is user responsibility or not, the problem is when an exception is raised in callback the process doesn't crash, no error is shown and the browser waits for response forever! 

BTW the previous version used to crash the process on callback exceptions so developers who write the code according to that would get confused when the connection freeze and there is no error in log output!

I used mongojs, so I can comment about that. find() callback worked as I expected but count() didn't. It just freeze the connection on exceptions.

**Comment by christkv** [comment]
I guess I'm confused because I cannot find a mongojs version that supports the latest driver. So would you mind just making a simple example gist for me with a package.json file so I can figure out why it's happening when you call count in mongojs versus not happening using the mongodb driver directly.

**Comment by rahbari** [comment]
Sorry for confusion, mongojs use mongodb ^2.0.45, so when you install it using npm it install the latest mongodb which is v2.2.1 and this version of mongodb driver use mongodb core 2, but v2.1.21 of the mongodb driver uses mongodb core 1.

please have a look at this thread:

https://github.com/mafintosh/mongojs/issues/317

**Comment by christkv** [comment]
issue is caused by thunky in mongojs, I opened a ticket for them to fix it and removed the wrapping of the callback in a nexttick. 

https://github.com/mafintosh/mongojs/issues/321
