### ISSUE TITLE
Possibly incorrect usage of socket timeout

### ISSUE THREAD

**Issue by zzanzare** [christkv/mongodb-core#140]
In method setSocketTimeout of Connection class (https://github.com/christkv/mongodb-core/blob/V2.2.1/lib/connection/connection.js#L119) it's using nodejs method setTimeout on a socket object (https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback). I believe this usage is in fact incorrect, because the socketTimeoutMS option of mongodb connection is specified as "The time in milliseconds to attempt a send or receive on a socket before the attempt times out." (https://docs.mongodb.com/manual/reference/connection-string/) whereas the setTimeout method of nodejs socket object "Sets the socket to timeout after timeout milliseconds of inactivity on the socket." which are two different things..

There seems to be some regular "keep alive" communication between mongodb npm module and the database which I wasn't able to track down, however it seems it's hardcoded to 10 seconds.. we had to set the socketTimeoutMS option to 11000, to have connections open "forever", otherwise they kept closing and opening every 10 seconds, which caused some other queries to take too long to finish. Also we had to implement our own "query timeout" mechanism to actually get the requested behavior - keeping the connection open, but not waiting for query responses for more than X ms.

It might be relevant to mention that we experienced this problem while connecting to a replication set.

**Comment by christkv** [comment]
That is expected behavior as the high availability sweep is defaulted to every ten seconds. if you set socketTimeout below the high availability sweep time you will get the timeouts you are experiencing since secondaries might not be exercised by anything but the status sweep. The latest driver logs a console warning if you did this by mistake.

https://github.com/christkv/mongodb-core/blob/2.0/lib/topologies/replset.js#L170
