### ISSUE TITLE
Dependency on kerberos@~0.0 breaks npm shrinkwrap

### ISSUE THREAD

**Issue by crispy1989** [christkv/mongodb-core#65]
Trying to `npm shrinkwrap` a package that depends on `mongodb-core`, either directly or indirectly, results in an error, and causes the shrinkwrap to fail:

```js
npm ERR! peer invalid: kerberos@~0.0, required by mongodb-core@1.2.26
```

Using npm version 3.5.1 .

**Comment by christkv** [comment]
Put a dependency on kerberos in your package to have it be wrapped up. However this seems like a bug in NPM as you would expect peerDependencies not to make NPM fail but just print a warning. You might want to open a ticket with NPM aswell.

**Comment by williamle8300** [comment]
I'm not familiar with Kerberos at all, so this is just a suggestion:

Would it possible if `mongo-core` made a dependency on `kerberos` (instead of declaring it as a peer dep)?

References:
https://github.com/npm/npm/issues/3066

**Comment by christkv** [comment]
no it was made a peer dependency because 99.9% of users do not need it and with NPM 3.0 it will just ignore the module if you have not specifically depended on it which is by design to avoid all the possibly associated confusion of it breaking on install due to missing libraries or compilers.

**Comment by gabegorelick** [comment]
> with NPM 3.0 it will just ignore the module if you have not specifically depended

Correct, but `npm shrinkwrap` is still broken with peer dependencies [1]. If you're using the peerDependency to inform users of an optional dependency, would you consider just having some documentation to depend on kerberos, e.g. in the README, instead of an explicit peerDependency?

[1] https://github.com/npm/npm/issues/5135

**Comment by williamle8300** [comment]
:+1:

**Comment by christkv** [comment]
It sucks that NPM has this bug, but I think the right place is for it to be fixed there. For now the obvious work around is to just depend on the kerberos module in your project or just preprocess the package.json files in your node_modules directory to strip out peer dependencies.

I'm sorry thats probably not the answer you hoped for but I want to give NPM a chance to fix this instead of loosing the useful information NPM 3.x supplies when doing npm install.

If I have time in the next couple of weeks I might try to just submit a PR on the matter as it seems it should just use the same codepath as npm install for the dependencies instead of what seems like a completely different set of logic.

**Comment by gabegorelick** [comment]
npm should definitely fix that bug, but what benefit does this
peerDependency actually provide over something in the README? Perhaps it's
a nice convenience to return an error when you have an incompatible version
of kerberos installed, but given that it looks like ~0.0 will match every
published version of that package, does the peerDependency actually offer
any benefit?

**Comment by lennym** [comment]
Would it not make more sense in this case to make kerberos an optionalDependency rather than a peer dependency?

From [the mongo documentation](http://mongodb.github.io/node-mongodb-native/2.0/getting-started/installation-guide/):

> This tells you that the driver could not resolve it’s peerDependency. However don’t worry. You only need the kerberos module if intend to use kerberos. In the case you need to you can add it to your package.json by doing the following for the case of the line above.

This sounds to me like kerberos is exactly optional.

**Comment by christkv** [comment]
optionalDependency will still try to build the module which is not what we want.

**Comment by gabegorelick** [comment]
What's the problem with not including it in the package.json at all?

**Comment by lennym** [comment]
I'd support that as a course of action. If users want to use kerberos they can install it, which is basically the current status anyway with npm@3, but it doesn't cause other things to break.

**Comment by triccardi-systran** [comment]
@gabegorelick if you remove it altogether from the package.json, then npm cannot help you if you install a `kerberos` with a version incompatible with mongodb-core code.
`peerDependency` is there for that: the author of mongodb-core can tell npm which version of the peer dependency is OK.

However, npm implementation is currently broken.

Since the `kerberos` package is also controlled by @christkv, then the risk of incompatibility is under control: @christkv  just has to not release an incompatible `kerberos` until npm@3 gets fixed. 
In this scenario, the peer dependency could be simply removed, and it would be safe, as long as people use the latest mongodb-core and npm@3 versions available at any time.
So it's not that safe...

**Comment by lennym** [comment]
Has anyone from npm actually accepted that this is a bug in npm, because it doesn't seem like one for me?

A peer dependency *is still a dependency*, the changes in npm@3 simply move the responsibility for resolving a peer dependency to the parent package. In this case, since kerberos is not required by mongo-core (citation: [mongo-core documentation](http://mongodb.github.io/node-mongodb-native/2.1/getting-started/installation-guide/#troubleshooting)) then it should not be defined as as a dependency. To effectively backdoor it as an optional dependency is to exploit a side-effect of the changes in npm@3 and is IMO not a proper semantic use of npm dependencies - in particular I think it should be an optional dependency, and so actually in control of the user rather than being completely a side-effect of the npm version installed.

Furthermore, I think npm's behaviour of throwing an error at `npm shrinkwrap` if dependencies are not met is correct, since as stated above, a peer dependency is still a dependency, and so the dependency tree is in a broken state if peer dependencies are not installed.

tl;dr - I don't believe npm's implementation is broken, I think the use of peer dependencies here is not consistent with their intended use.

**Comment by triccardi-systran** [comment]
@lennym 
The need is indeed to make `kerberos` an optional dependency, in the sense that the module is not needed, but can be used if present.
However npm `optionalDependencies` field adds an additional semantic to the previous definition: it forces npm to try by default to install the `optionalDependencies`, and if it fails to, it doesn't stop there and just ignores the error.

Previously, mongodb-core did use that field, but the "try install by default" is not great from a use point of view: most user get an big WARNING on each install because gcc or libkerberos is missing from their system; this is bad. Also, if ever it successfully install the dependency, it's still bad because it was *not* asked by the user.

So the current `optionalDependencies` is not what we want.


The `peerDependencies` in npm@3 are effectively optional now. It's said here by a npm developer: https://github.com/npm/npm/issues/3066#issuecomment-154161544
This is indeed not perfect because it can be considered a side-effect; but it's the best alternative we have now.
To satisfy your needs, a new `optionalPeerDependencies` should be introduced; but what would be the differences between that and the npm@3 current `peerDependencies` ? I believe there would be none.

The only reason to add a new `optionalPeerDependencies` would be to help existing modules explicitly migrate, to avoid any breakage.
But it's not what npm decided: they just changed the behavior of `peerDependencies` in npm@3 and warn about it to tell users to migrate.

So `peerDependencies` is what we want, we just need npm to fix their bugs...

**Comment by lennym** [comment]
Well if that is the *official* npm line, and not just an off-hand comment by @othiym23 then it is fair to say that npm have a bug, but I'm not certain that is the case. I'd like to see a more explicit statement of intent from npm about the future of peer dependencies. 

In particular, that issue you linked to a comment in is closed, and the related issues in npm (https://github.com/npm/npm/issues/10836 and https://github.com/npm/npm/issues/5135) show no indication of acceptance as a bug by anyone at npm.

Also, from the installation dialogue in npm@2.14.7:

> npm WARN peerDependencies in npm 3+. Your application **will need to** depend on it explicitly.

(emphasis mine) It certainly doesn't suggest that peer dependencies are being made optional, merely that the responsibility for resolution is shifted to the parent package.

**Comment by othiym23** [comment]
`peerDependencies` are the wrong solution to a situation where you want to take advantage of something only if it's installed. They're required, and are a constraint that says, "this package must have that package installed in order to function (e.g. this package is a plugin for that package), but it's up to you to depend on it". If the constraint isn't satisfied, `npm ls` should show the unsatisfied `peerDependency` as missing and `npm shrinkwrap` should similarly error.

Instead, if the dependency is optional, make it an `optionalDependency`, or, if it's something that only a small number of users are going to need (but they're going to _need_ it, like an auth strategy), write a little opportunistic loader using `require` within a try / catch block to try to load that module, and document that it's there.

**Comment by tjconcept** [comment]
`optionalDependency` intuitively sounds like the right thing, but why is npm installing those be default? That does not sound intuitive to me.

**Comment by christkv** [comment]
@tjconcept @othiym23 I would agree with Thomas here `optionalDependency` seems to have the wrong semantics. My problem is it causes a torrent of user issues where people log tickets because they don't understand that the errors emitted by the kerberos module build did not cause the npm install to fail.

**Comment by lennym** [comment]
I think given the objectives here are as follows:

* Do not require users to install kerberos
* Support users who have installed kerberos
* Ensure users who have kerberos installed have a compatible version

Proposal:

* Remove kerberos from dependencies.
* Add code at https://github.com/christkv/mongodb-core/blob/5166f0fdc2e1c7b718ae01b3d0670fd582054197/lib/auth/gssapi.js#L25-L29 and https://github.com/christkv/mongodb-core/blob/5166f0fdc2e1c7b718ae01b3d0670fd582054197/lib/auth/sspi.js#L25-L29 that checks the version and errors if an incompatible version is installed.

This is very close to what @othiym23 is proposing above.

These seem to be the only two places in the repo where kerberos is required - certainly that I can find - so it would not be a significant change to support this.

**Comment by christkv** [comment]
Well this seems utterly contrarian to using a package manager and dependencies declaration.

**Comment by tjconcept** [comment]
I agree that what @lennym and @othiym23 proposes are better user-wise than the current situation, but it's a hack.

I can see the case for "always install this module, but if it fails, don't worry", though I hope they are rare. But that's not an optional dependency as it is not a dependency. At most "optional package".
At its worst you could have optional dependencies be either "install by default" or "install by request".

**Comment by lennym** [comment]
I'm not trying to claim it's a *nice* solution at all, it's just the best solution I have that doesn't involve waiting for npm to possibly implement some possible future functionality (optional peer dependencies).

I'm only coming at this as someone who wants to be able to do reproducible installations without installing a module which I neither want nor need (and as is mentioned above, is non-trivial to install).

**Comment by othiym23** [comment]
npm isn't going to gain support for `optionalPeerDependencies`. In this case, it would also be expressing the relationship exactly backwards – this use case isn't describing a `peerDependency` relationship – this module isn't a plugin Kerberos, Kerberos is a plug gable auth strategy. If anything, the Kerberos support should be broken out into a separate package that has a `peerDependency` constraint on `mongodb-core`.

The CLI team _will_ be adding support for suppressing error output for failed `optionalDependency` builds, to make clearer that those failures are expected and unremarkable, and we have been fixing issues in how shrinkwrap deals with `optionalDependencies` in the shrinkwrapped tree. If you run into bugs there, you should encourage users to try a newer version of npm, or file bugs if the misbehavior persists.

I'm confused as to why you're dismissing `optionalDependencies`, as this is what they're designed for. A failed `optionalDependency` install won't fail the whole install, and the semantics would seem to capture exactly your intent: if this package can be installed on this host, install it.

**Comment by christkv** [comment]
I'm not dismissing `optionalDependency` I'm saying that it confuses user who think the module did not install. The fix might be as easy as a very loud end message for npm install where it notifies you that the packaged was installed successfully and that the following x optional packages did not install successfully but that they are not required for the module to work properly

I think it's mainly a UX issues, people see the error output and assumes the install failed and then open a ticket.

**Comment by tjconcept** [comment]
> npm isn't going to gain support for `optionalPeerDependencies`. In this case, it would also be expressing the relationship exactly backwards – this use case isn't describing a `peerDependency` relationship – this module isn't a plugin for Kerberos, Kerberos is a pluggable auth strategy. If anything, the Kerberos support should be broken out into a separate package that has a `peerDependency` constraint on `mongoldb-core`.

Makes sense. It is not a dependency.

> if this package can be installed on this host, install it

That is not the intent to my knowledge. At least it's not what I would think of `optionalDependencies` neither is it what I want to do with Kerberos.

It's still weird though, that optional dependencies are installed by `npm install`, but that's another story.

**Comment by othiym23** [comment]
> That is not the intent to my knowledge. At least it's not what I would think of `optionalDependencies` neither is it what I want to do with Kerberos.

What is your view of the intent of `optiinalDependencies`? My view of their semantics is that they're a constraint and directive to the installer that the listed packages should be installed at the specified version, but if they fail to install, that shouldn't be treated as an error by the installer.

**Comment by tjconcept** [comment]
No doubt I would expect "optional dependencies" to mean: "this is something you can choose to install if you want".
The word "dependency" makes it a bit confusing. I thought it was more like Debian's "suggested".

**Comment by triccardi-systran** [comment]
As @othiym23 said, we got it backward:
> npm isn't going to gain support for optionalPeerDependencies. In this case, it would also be expressing the relationship exactly backwards – this use case isn't describing a peerDependency relationship – this module isn't a plugin for Kerberos, Kerberos is a pluggable auth strategy. If anything, the Kerberos support should be broken out into a separate package that has a peerDependency constraint on mongodb-core.

`peerDependencies` was created for modules that are plugins for other modules, and this is the way to express compatibility with the module they plug into.

So, what we need is a `mongodb-kerberos` module, with peer dependency on `mongodb` (peer dependency on`mongodb-core` is alas not possible (I tested): npm requires peerDependencies to be satisfied by the direct parent module only, not a grandparent; I think this constraint could be relaxed; our case is the perfect use-case; we should open a feature request on npm); and the people requiring `mongodb` with support for kerberos should depend on both `mongodb` and `mongodb-kerberos`, and pass somehow the `mongodb-kerberos` module (or an instanciation of one) to `mongodb`, which would then pass it to `mongodb-core`.

This is not perfect because the real peer dependency constraint is on `mongodb-core` and not `mongodb`, but it should still work.

I don't know how to cleanly migrate to this implementation though: it will be a breaking change for `mongodb` users depending on kerberos.

**Comment by christkv** [comment]
Looks like only reasonable solution is optionalDependency and just have to deal with users being confused. All the other proposed solutions either increase complexity or will cause confusion about what module to use. 

Looks like I'll have to create my own package key and enforce it in the driver.

**Comment by triccardi-systran** [comment]
The optionalDependency solution has multiple issues:
1/ scary warnings/errors
2/ slower npm install
3/ uncontrolled installation: if ever `kerberos` is successfully installed, then it will be used and loaded, even if the user doesn't want that. The user doesn't always controls its build environment.

The corrected peerDependency solution does increase the complexity a little for the users, but at least they explicitly control if kerberos is built/loaded/used.


In any case, the current state is wrong, and should at least be reverted back to optionalDependencies, to fix users of npm shrinkwrap and npm ls (I'm one of them...).

Correct peerDependency could be introduced later in a mongodb 3.0 version.

**Comment by gabegorelick** [comment]
For the short term I will again recommend just removing it from
package.json all together. Having it as any kind of dep solves a
theoretical problem if there's ever a release of kerberos that is
incompatible. But the current dep range matches all versions anyway and it
doesn't look like a new (breaking) version is getting released any time
soon. And as someone else mentioned, the packages have the same maintainer.

Ask yourself which problem is worse: people complaining that their installs
are broken from kerberos failing or people complaining they've accidentally
used the wrong version of kerberos with mongo. I think the latter is far
less common.

**Comment by christkv** [comment]
I decided to roll my own require_optional package that uses the custom peerOptionalDependencies field in the package.json. Should be out in the next 2.1.x release.
