### ISSUE TITLE
Since 1df3dd3 tailable cursors get retried in a tight loop causing high load

### ISSUE THREAD

**Issue by autopulated** [christkv/mongodb-core#87]
Since 1df3dd3a0365213d199448e3ff93e3cb4235ea2a if a tailable cursor returns no documents, `nextFunction` is [called again immediately](https://github.com/christkv/mongodb-core/blob/1.3/lib/cursor.js#L596).

This seems to be contrary to [a comment](https://github.com/christkv/mongodb-core/blob/1.3/lib/cursor.js#L582-L584) in the source, and I don't think it's the right behaviour: the higher level module should decide when to retry.

(I believe this is the root cause of https://github.com/scttnlsn/mubsub/issues/49)

**Comment by christkv** [comment]
The problem is really that the tailable cursor code was broken. The cursor is actually still alive and this is what is causing the retries (it's been a long running bug in the driver). Now the question is do you set awaitData on the cursor this will cause the cursor to wait for a little before returning, breaking up the tight loop you are seeing.

If they use 3.2.x of mongodb they can also use the `maxAwaitTimeMS` function on the cursor.

```js
collection.find({})
  .maxAwaitTimeMS(5000)
  .addCursorFlag('awaitData', true)
  .addCursorFlag('tailable', true);
```

This activates the awaitData flag, sets the cursor as tailable and makes the cursor wait for 5000 ms before returning on an en empty getMore (it will wait for 5000ms for new documents).

**Comment by autopulated** [comment]
If mongodb is < 3.2, is the only option to go back to the 'broken' version then?

**Comment by christkv** [comment]
@autopulated no adding awaitData will still do the right thing on 3.0 or earlier just that you cannot control the period. There really are no situations where awaitData should not be set.

**Comment by autopulated** [comment]
OK got it, thanks!

**Comment by christkv** [comment]
let me know if it has the desired effect

**Comment by autopulated** [comment]
Works for me :+1:

**Comment by christkv** [comment]
@autopulated I think you should expose the maxAwaitTimeMS is possible as it will help you adjust the behavior for 3.2 and higher :)
